In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

from pathlib import Path

sns.set_theme(style="whitegrid")

IMAGES = Path("../output/figures")
IMAGES.mkdir(exist_ok=True)

plt.rcParams["figure.figsize"]=(10,5)
plt.rcParams["axes.titlesize"]=13
plt.rcParams["axes.titleweight"]="bold"
plt.rcParams["figure.figsize"] = (10,5)

In [2]:
sanpham = pd.read_csv("../data/clean/dm_san_pham_clean.csv")
vitri = pd.read_csv("../data/clean/dm_vi_tri_clean.csv")
tonkho = pd.read_csv("../data/clean/xnk_ton_kho_clean.csv")
cham = pd.read_csv("../data/clean/log_cham_hang.csv")
xuatkho = pd.read_csv("../data/clean/xnk_xuat_kho_clean.csv")
nhapkho = pd.read_csv("../data/clean/xnk_nhap_kho_clean.csv")

C:\Users\anhkh\AppData\Local\Temp\ipykernel_19256\629453351.py:1: DtypeWarning: Columns (6,32,39) have mixed types. Specify dtype option on import or set low_memory=False.
  sanpham = pd.read_csv("../data/clean/dm_san_pham_clean.csv")
C:\Users\anhkh\AppData\Local\Temp\ipykernel_19256\629453351.py:5: DtypeWarning: Columns (9,31,34) have mixed types. Specify dtype option on import or set low_memory=False.
  xuatkho = pd.read_csv("../data/clean/xnk_xuat_kho_clean.csv")
C:\Users\anhkh\AppData\Local\Temp\ipykernel_19256\629453351.py:6: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  nhapkho = pd.read_csv("../data/clean/xnk_nhap_kho_clean.csv")

In [3]:
vitriA = pd.read_csv("../data/clean/12473657/vi_tri_kho12473657.csv")

In [4]:
classic = pd.read_csv("../data/process/classic_feature.csv")

In [5]:
rawvitri = pd.read_csv("../data/raw/dm_vi_tri.csv")

In [6]:
KHO_ID = 12473657

so_day = (
    vitri.query("kho_id == @KHO_ID")["day_ke_id"]
    .nunique()
)

print("Số dãy:", so_day)

Số dãy: 63

In [7]:
sorted(
    vitri.query("kho_id == @KHO_ID")["day_ke_id"].unique()
)

[12473741,
 12473743,
 12473745,
 12473747,
 12473749,
 12473751,
 12473753,
 12473755,
 12473757,
 12473759,
 12473761,
 12473763,
 12473765,
 12473767,
 12473769,
 12473771,
 12473773,
 12473775,
 12473777,
 12473779,
 12473781,
 12473783,
 12473785,
 12473787,
 12473789,
 12473791,
 12473793,
 12473795,
 12473797,
 12473799,
 12473801,
 12473803,
 12473805,
 12473807,
 12473809,
 12473811,
 12736777,
 13695465,
 13695479,
 14022130,
 14022136,
 14022148,
 14022152,
 14022172,
 14022187,
 14022190,
 14022193,
 14022199,
 14022203,
 14022647,
 23283163,
 23283169,
 23956284,
 24933113,
 25151206,
 45047985,
 45048611,
 45049106,
 45050583,
 45438829,
 45493696,
 45493793,
 46018702]

In [8]:
classic.columns

Index(['san_pham_id', 'vi_tri_id', 'kho_id', 'nganh_hang_id', 'gw_san_pham',
       'cbm_san_pham', 'so_ngay_su_dung', 'tong_nhap', 'ton_kho', 'tong_xuat',
       'tan_suat_xuat', 'abc_class', 'abc_score', 'ti_le_cham_hang',
       'shelf_life_days', 'remaining_shelf_life_days', 'inventory_age_days',
       'day_ke_id', 'ma_so_vi_tri', 'tang', 'vi_tri_type_id',
       'Vong_Quay_tonkho'],
      dtype='object')

In [9]:
classic.groupby('san_pham_id')['vi_tri_type_id'].nunique().value_counts()
#classic.groupby('san_pham_id')['vi_tri_id'].count().describe()

vi_tri_type_id
3    4170
1    1261
4     945
2     933
5     764
6     254
7      12
Name: count, dtype: int64

In [10]:
khoraw = (
    rawvitri.query("kho_id == 12630830")
    .sort_values(
        ["tang", "day_ke_id", "ma_so_vi_tri"]
    )
)

khoraw

,auto_id,kho_id,day_ke_id,ma_so_vi_tri,tang,dai,rong,cao,vi_tri_type_id,vi_tri_seq_id,...,cbm_max,trang_thai_id,ghi_chu,deleted,created,created_by,created_by_function,last_updated,last_updated_by,last_updated_by_function
5636,49648437,12630830,49647666,KMSLL,0,0.0,0.0,0.0,1,0,...,0.0,1,NaN,0,2026-05-21 15:18:11.162422,810_IT2,2005,2026-05-21 15:18:11.162422,810_IT2,2005
21034,49658977,12630830,49647766,0-0-0,0,0.0,0.0,0.0,3,0,...,0.0,1,NaN,0,2026-05-21 15:18:40.853925,810_IT2,2005,2026-05-21 15:18:40.853925,810_IT2,2005
951,49657201,12630830,49647766,HZ1,0,0.0,0.0,0.0,15,0,...,0.0,1,NaN,0,2026-05-21 15:18:34.44811,810_IT2,2005,2026-06-24 15:35:17.767637,810_IT1,2005
1044,49657199,12630830,49647766,HZ2,0,0.0,0.0,0.0,15,0,...,0.0,1,NaN,0,2026-05-21 15:18:34.44198,810_IT2,2005,2026-06-24 15:35:29.142445,810_IT1,2005
796,49657197,12630830,49647766,HZ3,0,0.0,0.0,0.0,15,0,...,0.0,1,NaN,0,2026-05-21 15:18:34.436155,810_IT2,2005,2026-06-24 15:35:38.829981,810_IT1,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5359,49648383,12630830,49647782,S01306,6,100.0,120.0,145.0,2,0,...,0.0,1,NaN,0,2026-05-21 15:18:11.080421,810_IT2,2005,2026-05-21 15:18:11.080421,810_IT2,2005
6290,49648473,12630830,49647782,S01326,6,100.0,120.0,145.0,2,0,...,0.0,1,NaN,0,2026-05-21 15:18:11.216306,810_IT2,2005,2026-05-21 15:18:11.216306,810_IT2,2005
6325,49648467,12630830,49647782,S01366,6,100.0,120.0,145.0,2,0,...,0.0,1,NaN,0,2026-05-21 15:18:11.207378,810_IT2,2005,2026-05-21 15:18:11.207378,810_IT2,2005
6233,49648461,12630830,49647782,S01386,6,100.0,120.0,145.0,2,0,...,0.0,1,NaN,0,2026-05-21 15:18:11.198678,810_IT2,2005,2026-05-21 15:18:11.198678,810_IT2,2005
5867,49648455,12630830,49647782,S01426,6,100.0,120.0,145.0,2,0,...,0.0,1,NaN,0,2026-05-21 15:18:11.189536,810_IT2,2005,2026-05-21 15:18:11.189536,810_IT2,2005

In [11]:
# khoraw.to_csv(
#     "../data/clean/12630830/vi_tri_kho12630830.csv",
#     index=False,
#     encoding="utf-8-sig"
# )

In [12]:
kho = (
    vitri.query("kho_id == 12473657")
    .sort_values(
        ["tang", "day_ke_id", "ma_so_vi_tri"]
    )
)

kho

,auto_id,kho_id,day_ke_id,ma_so_vi_tri,tang,dai,rong,cao,vi_tri_type_id,vi_tri_seq_id,...,gw_max,cbm_max,trang_thai_id,deleted,created,created_by,created_by_function,last_updated,last_updated_by,last_updated_by_function
8648,12491552,12473657,12473741,E06-008-01,0,95.148703,112.694835,123.035765,1,0,...,0.0,3.274418e+08,1067,1,2025-02-25 15:54:44.743,admin,2005,2025-06-12 22:22:58.82,DTB815HTDT,2005
8647,12491550,12473657,12473741,E06-008-02,0,95.148703,112.694835,123.035765,1,0,...,0.0,3.274418e+08,1067,1,2025-02-25 15:54:44.72,admin,2005,2025-06-12 22:23:00.023,DTB815HTDT,2005
8646,12491548,12473657,12473741,E06-008-03,0,95.148703,112.694835,123.035765,1,0,...,0.0,3.274418e+08,1067,1,2025-02-25 15:54:44.7,admin,2005,2025-06-12 22:23:01.227,DTB815HTDT,2005
8645,12491546,12473657,12473741,E06-009-01,0,95.148703,112.694835,123.035765,1,0,...,0.0,3.274418e+08,1067,1,2025-02-25 15:54:44.68,admin,2005,2025-06-12 22:23:02.397,DTB815HTDT,2005
8642,12491540,12473657,12473741,E06-010-01,0,95.148703,112.694835,123.035765,1,0,...,0.0,3.274418e+08,1067,1,2025-02-25 15:54:44.62,admin,2005,2025-06-12 22:23:21.163,DTB815HTDT,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15983,12490822,12473657,12473795,R26-077-10,10,104.924440,113.879711,141.201054,2,77,...,0.0,1.860000e+06,1,0,2025-02-25 15:54:37.43,admin,2005,2025-09-19 08:26:54.849925,DTB815HTDT,2005
15840,12490824,12473657,12473795,R26-079-10,10,104.924440,113.879711,141.201054,2,79,...,0.0,1.860000e+06,1,0,2025-02-25 15:54:37.45,admin,2005,2025-09-19 08:26:54.829289,DTB815HTDT,2005
15982,12490826,12473657,12473795,R26-083-10,10,104.924440,113.879711,141.201054,2,83,...,0.0,1.860000e+06,1,0,2025-02-25 15:54:37.47,admin,2005,2025-09-19 08:26:54.807581,DTB815HTDT,2005
16079,12490828,12473657,12473795,R26-085-10,10,104.924440,113.879711,141.201054,2,85,...,0.0,1.860000e+06,1,0,2025-02-25 15:54:37.487,admin,2005,2025-09-19 08:26:54.78352,DTB815HTDT,2005
16078,12490830,12473657,12473795,R26-089-10,10,104.924440,113.879711,141.201054,2,89,...,0.0,1.860000e+06,1,0,2025-02-25 15:54:37.507,admin,2005,2025-09-19 08:26:54.763337,DTB815HTDT,2005

In [13]:
khoAton = (
    tonkho.query("kho_id == 12473657")
    .sort_values(
        ["so_kien_nhap"]
    )
)

khoAton

,auto_id,chu_hang_id,kho_id,vi_tri_id,so_lpn,nhap_kho_id,san_pham_id,so_po,ngay_san_xuat,ngay_het_han,...,trang_thai_lo_hang_id,nv_putaway,ngay_gio_putaway,deleted,created,created_by,created_by_function,last_updated,last_updated_by,last_updated_by_function
146534,27282309,12473661,12473657,12478727,LPN0110040,24987103,20124321,16286394,NaN,NaN,...,1,NaN,NaN,0,2025-10-12 15:36:25.716956,DTB815VTH2,5001,2025-12-15 10:35:56.300196,admin,5023
144008,24134900,12473661,12473657,12488526,LPN0047815,23813712,12504791,95333813,2025-08-06 00:00:00,2029-08-06 00:00:00,...,1,DTB815TK07,2025-08-28 09:28:30.063414,0,2025-09-02 17:24:01.796947,DTB815VTH1,5001,2025-10-01 12:18:12.506308,admin,5023
49632,13312521,12473661,12473657,12478793,LPN0110050,13308716,13308640,15763520,NaN,NaN,...,1,DTB815TK04,2025-05-18 10:53:16.54,0,2025-05-18 10:53:16.537,DTB815TK04,FPDA_302_SGC_S1_Putaway_Pallet_Xac_Nhan,2025-12-11 13:32:11.110984,DTB815HTDT,5001
381888,36615850,12473661,12473657,12478383,LPN0133951,36360395,12502943,98499282,2026-01-02 00:00:00,2027-01-02 00:00:00,...,1,DTB815TK12,2026-01-08 08:51:17.648752,0,2026-01-08 08:51:17.648752,DTB815TK12,FPDA_302_A_S1,2026-01-08 08:51:17.648752,DTB815TK12,FPDA_302_A_S1
381886,36615934,12473661,12473657,12483175,LPN0135129,36559292,12504581,98646369,2026-01-03 00:00:00,2029-01-03 00:00:00,...,1,DTB815XH10,2026-01-08 08:50:53.22297,0,2026-01-08 08:52:04.25587,DTB815XH10,FPDA_501_SGC_S1,2026-01-08 08:52:04.25587,DTB815XH10,FPDA_501_SGC_S1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668504,52998218,12854885,12473657,12853309,LPN0218986,52361299,27778647,101784964,2026-05-28 00:00:00,2028-05-27 00:00:00,...,1,NaN,NaN,0,2026-06-19 08:59:18.698485,DTB815SLL,4001,2026-06-19 08:59:18.698485,DTB815SLL,4001
55090,20653983,12473661,12473657,14036665,LPN0025900,20653863,12506085,94134435,2025-06-17 00:00:00,2026-06-17 00:00:00,...,21,DTB815TK01,2025-07-03 11:53:46.726869,0,2025-07-03 11:53:46.726869,DTB815TK01,FPDA_302_A_S1,2025-07-03 11:53:46.726869,DTB815TK01,FPDA_302_A_S1
56602,20694183,12473661,12473657,14036665,LPN0008014,20693950,12506085,94134435,2025-06-20 00:00:00,2026-06-20 00:00:00,...,21,DTB815TK01,2025-07-04 11:15:57.140803,0,2025-07-04 11:15:57.140803,DTB815TK01,FPDA_302_A_S1,2025-07-04 11:15:57.140803,DTB815TK01,FPDA_302_A_S1
408559,37302323,12854885,12473657,12475489,LPN0111325,36852696,36693469,98726871,NaN,NaN,...,1,NaN,NaN,0,2026-01-12 17:54:36.965167,DTB815VTH1,5001,2026-01-12 18:28:46.420156,DTB815SLL,4001
570217,44550414,12854885,12473657,12853309,LPN0170198,44346854,27778804,100393502,2026-03-27 00:00:00,2027-03-27 00:00:00,...,1,NaN,NaN,0,2026-04-03 11:07:10.171615,DTB815XLD2,4001,2026-04-06 08:37:10.431601,DTB815XLD1,4002

In [14]:
tonkho.columns

Index(['auto_id', 'chu_hang_id', 'kho_id', 'vi_tri_id', 'so_lpn',
       'nhap_kho_id', 'san_pham_id', 'so_po', 'ngay_san_xuat', 'ngay_het_han',
       'line_item', 'ma_key_lo_hang', 'ngay_nhap_kho_root', 'so_kien_nhap',
       'sl_nhap_chan', 'sl_nhap_le', 'sl_nhap_all_special', 'so_kien_xuat',
       'sl_xuat_chan', 'sl_xuat_le', 'sl_xuat_all_special', 'so_kien_dc',
       'sl_dc_chan', 'sl_dc_le', 'sl_dc_all_special', 'so_kien_tach',
       'don_gia', 'nw', 'gw', 'cbm', 'trang_thai_lo_hang_id', 'nv_putaway',
       'ngay_gio_putaway', 'deleted', 'created', 'created_by',
       'created_by_function', 'last_updated', 'last_updated_by',
       'last_updated_by_function'],
      dtype='object')

In [17]:
vitriA["day_ke_id"].nunique()

63

In [24]:
sorted(vitriA["day_ke_id"].unique())

[12473741,
 12473743,
 12473745,
 12473747,
 12473749,
 12473751,
 12473753,
 12473755,
 12473757,
 12473759,
 12473761,
 12473763,
 12473765,
 12473767,
 12473769,
 12473771,
 12473773,
 12473775,
 12473777,
 12473779,
 12473781,
 12473783,
 12473785,
 12473787,
 12473789,
 12473791,
 12473793,
 12473795,
 12473797,
 12473799,
 12473801,
 12473803,
 12473805,
 12473807,
 12473809,
 12473811,
 12736777,
 13695465,
 13695479,
 14022130,
 14022136,
 14022148,
 14022152,
 14022172,
 14022187,
 14022190,
 14022193,
 14022199,
 14022203,
 14022647,
 23283163,
 23283169,
 23956284,
 24933113,
 25151206,
 45047985,
 45048611,
 45049106,
 45050583,
 45438829,
 45493696,
 45493793,
 46018702]

In [25]:
day_summary = (
    vitriA
    .groupby("day_ke_id")
    .agg(
        so_vi_tri=("auto_id", "count"),
        tang_min=("tang", "min"),
        tang_max=("tang", "max"),
    )
    .reset_index()
    .sort_values("day_ke_id")
)

day_summary

    day_ke_id  so_vi_tri  tang_min  tang_max
0    12473741         49         0         0
1    12473743         44         0         1
2    12473745        180         1        10
3    12473747        288         1        10
4    12473749        288         1        10
..        ...        ...       ...       ...
58   45050583         36         1         4
59   45438829         40         1         4
60   45493696         40         1         4
61   45493793         40         1         4
62   46018702         20         1         4

[63 rows x 4 columns]

In [38]:
vitriA.loc[
    vitriA["day_ke_id"] == 12473809,
    ["ma_so_vi_tri", "tang","vi_tri_seq_id","vi_tri_type_id"]
].sort_values(["tang", "ma_so_vi_tri","vi_tri_seq_id","vi_tri_type_id"])

     ma_so_vi_tri  tang  vi_tri_seq_id  vi_tri_type_id
2712        RD-01     1              1               1
2713        RD-02     1              2               1
2714        RD-03     1              3               1
2715        RD-04     1              4               1
2716        RD-05     1              5               1
...           ...   ...            ...             ...
2843        RD-96     1             96               1
2844        RD-97     1             97               1
2845        RD-98     1             98               1
2846        RD-99     1             99               1
2847     RD000083     1             83               1

[136 rows x 4 columns]

In [45]:
active_sku = set(tonkho["san_pham_id"].unique())

active_sku |= set(xuatkho["san_pham_id"].dropna().unique())

active_sku |= set(nhapkho["san_pham_id"].dropna().unique())

active_sku |= set(cham["san_pham_id"].dropna().unique())

active_sku = pd.Series(list(active_sku))

print(len(active_sku))

8339

In [49]:
KHO_ID = 12473657

active_sku = set(
    tonkho.loc[
        tonkho["kho_id"] == KHO_ID,
        "san_pham_id"
    ].dropna().unique()
)

active_sku |= set(
    xuatkho.loc[
        xuatkho["kho_id"] == KHO_ID,
        "san_pham_id"
    ].dropna().unique()
)

# Chỉ thêm nếu bảng châm hàng thật sự có san_pham_id và kho_id
active_sku |= set(
    cham.loc[
        cham["kho_id"] == KHO_ID,
        "san_pham_id"
    ].dropna().unique()
)

SPkhoA = (
    pd.Series(sorted(active_sku), name="san_pham_id")
)

print(len(SPkhoA))
SPkhoA

7146

0       12501027
1       12501029
2       12501031
3       12501033
4       12501035
          ...
7141    53471135
7142    53471137
7143    53471139
7144    53471141
7145    53676781
Name: san_pham_id, Length: 7146, dtype: int64

In [53]:
active_df = pd.DataFrame({
    "san_pham_id": list(active_sku)
})

SPkhoA = (
    active_df.merge(
        sanpham,
        left_on="san_pham_id",
        right_on="auto_id",
        how="left"
    )
    .sort_values(
        ["nganh_hang_id","loai_san_pham_id", "ma_san_pham"]
    )
    .reset_index(drop=True)
)

SPkhoA

,san_pham_id,auto_id,chu_hang_id,nhom_nganh_hang_id,nganh_hang_id,loai_san_pham_id,don_vi_tinh_id,don_vi_tinh_thung_id,ma_san_pham,ten_san_pham,...,pcs_cao,trang_thai_id,san_pham_type_id,deleted,created,created_by,created_by_function,last_updated,last_updated_by,last_updated_by_function
0,41762829,41762829.0,25707284.0,0.0,0.0,0.0,12499665.0,0,40001989.0,SP0001989,...,0.0,1.0,1,0.0,01:50.4,DTB815VTH2,2008.0,02:51.3,DTB815VTH2,2008
1,44509535,44509535.0,25707284.0,0.0,0.0,0.0,12499665.0,0,40002319.0,SP0002319,...,0.0,1.0,1,0.0,17:50.3,DTB815VTH2,2008.0,17:50.3,DTB815VTH2,2008
2,23794513,23794513.0,23794439.0,0.0,0.0,0.0,0.0,0,40002407.0,SP0002407,...,0.0,1.0,1,0.0,25:33.5,tks_tamdtk,2008.0,25:33.5,tks_tamdtk,2008
3,20208291,20208291.0,12473661.0,0.0,0.0,0.0,12499665.0,12499668,40006384.0,SP0006384,...,0.0,1.0,1,0.0,32:34.0,tks_tamdtk,2008.0,56:31.6,it_ngochb,scripts 1 to 2
4,40316950,40316950.0,25707284.0,0.0,0.0,0.0,12499665.0,0,40016087.0,SP0016087,...,0.0,1.0,1,0.0,04:05.9,DTB815VTH2,2008.0,04:28.6,DTB815VTH2,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7141,48268601,48268601.0,12854885.0,0.0,27806546.0,27808039.0,12499665.0,0,40002689.0,SP0002689,...,0.0,1.0,1,0.0,00:12.9,DTB815VTH1,2008.0,00:12.9,DTB815VTH1,2008
7142,49582371,49582371.0,12854885.0,0.0,27806546.0,27808039.0,12499665.0,0,40003658.0,SP0003658,...,0.0,1.0,1,0.0,46:17.0,DTB815VTH1,2008.0,58:20.4,DTB815VTH2,2008
7143,43963422,43963422.0,12854885.0,0.0,27806546.0,27808039.0,12499665.0,0,40003901.0,SP0003901,...,0.0,1.0,1,0.0,11:43.2,DTB815VTH1,2008.0,11:43.2,DTB815VTH1,2008
7144,41294288,41294288.0,12854885.0,0.0,27806546.0,27808039.0,12499665.0,0,40015174.0,SP0015174,...,0.0,1.0,1,0.0,24:38.4,DTB815VTH2,2008.0,24:38.4,DTB815VTH2,2008
7145,27771509,27771509.0,12854885.0,0.0,27806546.0,27808039.0,12499665.0,0,40022437.0,SP0022437,...,0.0,1.0,1,0.0,14:59.2,DTB815HTDT,2008.0,16:29.3,DTB815VTH2,2008

In [54]:
SPkhoA.to_csv(
    "../data/clean/12473657/san_pham_kho12473657.csv",
    index=False,
    encoding="utf-8-sig"
)

In [55]:
tonkho.columns

Index(['auto_id', 'chu_hang_id', 'kho_id', 'vi_tri_id', 'so_lpn',
       'nhap_kho_id', 'san_pham_id', 'so_po', 'ngay_san_xuat', 'ngay_het_han',
       'line_item', 'ma_key_lo_hang', 'ngay_nhap_kho_root', 'so_kien_nhap',
       'sl_nhap_chan', 'sl_nhap_le', 'sl_nhap_all_special', 'so_kien_xuat',
       'sl_xuat_chan', 'sl_xuat_le', 'sl_xuat_all_special', 'so_kien_dc',
       'sl_dc_chan', 'sl_dc_le', 'sl_dc_all_special', 'so_kien_tach',
       'don_gia', 'nw', 'gw', 'cbm', 'trang_thai_lo_hang_id', 'nv_putaway',
       'ngay_gio_putaway', 'deleted', 'created', 'created_by',
       'created_by_function', 'last_updated', 'last_updated_by',
       'last_updated_by_function'],
      dtype='object')

In [1]:
import pandas as pd

df = pd.read_csv("../data/clean/log_cham_hang.csv", low_memory=False)

print(df["auto_id"].duplicated().sum())

109